require_relative "./config"

namespace :db do
  desc "Create the database"
  task :create do
    `createdb #{Config::DB_NAME}`
  end

  desc "Drop the database"
  task :drop do
    `dropdb #{Config::DB_NAME}`
  end

  desc "Load the schema from `create_schema.sql`"
  task :migrate do
    `psql #{Config::DB_NAME} < create_schema.sql`
  end

  desc "Database console"
  task :console do
    system("psql #{Config::DB_NAME}")
  end
end
